version: "3"

services:
  auth:
    container_name: sabin/auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
